version: '3.4'

services:
  keeptodoistsync:
    image: keeptodoistsync
    restart: unless-stopped
    volumes:
      - ./config:/run/app_secrets:ro
      - app_state:/run/app_state
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  app_state:
