version: '3.4'

services:
  keeptodoistsync:
    image: keeptodoistsync
    restart: unless-stopped
    volumes:
      - app_state:/run/app_state
      - ./config:/run/secrets
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  app_state:
