version: '3.4'

secrets:
  google_username:
    file: ./config/google_username.txt
  google_password:
    file: ./config/google_password.txt

services:
  keeptodoistsync:
    image: keeptodoistsync
    secrets:
      - google_username
      - google_password
    volumes:
      - app_state:/run/app_state
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  app_state:
